// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiUQIy38Bv9LR-IGfFCVNTeCQShHh6Esk',
    appId: '1:1002887542158:web:dc72a752c54af4e24260df',
    messagingSenderId: '1002887542158',
    projectId: 'health-manager-514b1',
    authDomain: 'health-manager-514b1.firebaseapp.com',
    storageBucket: 'health-manager-514b1.appspot.com',
    measurementId: 'G-52WX2TTHJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCio4ENOF1BeRooUciUFcH7F8QBEOVH6cA',
    appId: '1:1002887542158:android:866bf557d676d1b44260df',
    messagingSenderId: '1002887542158',
    projectId: 'health-manager-514b1',
    storageBucket: 'health-manager-514b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANLSyWhte1MSMUzAO24yD9r3UlxuYoKOg',
    appId: '1:1002887542158:ios:e05db1456e9f5d114260df',
    messagingSenderId: '1002887542158',
    projectId: 'health-manager-514b1',
    storageBucket: 'health-manager-514b1.appspot.com',
    iosBundleId: 'com.example.healthManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANLSyWhte1MSMUzAO24yD9r3UlxuYoKOg',
    appId: '1:1002887542158:ios:2db1781de1dea1634260df',
    messagingSenderId: '1002887542158',
    projectId: 'health-manager-514b1',
    storageBucket: 'health-manager-514b1.appspot.com',
    iosBundleId: 'com.example.healthManager.RunnerTests',
  );
}
